"""config/stadiums.yaml, generated by code (BUILD_PLAN Phase 1 item 2, DATA-13).

One row per (stadium_id, stadium name) in the schedules: nflverse sometimes files a venue
under another venue's ID (a London game under a US team's stadium_id), so the name is part
of the key. Roof values are read from the schedules per game. Coordinates come only from
Wikidata: from an exact label/alias match, or from an item the user approved in
config/stadium_overrides.yaml. Time zone is computed from coordinates with timezonefinder.
Anything else stays blank and is listed for review."""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path
from typing import Any, Protocol

import polars as pl
import yaml
from timezonefinder import TimezoneFinder

from ge.config import REPO_ROOT, ElevationUnits, WikidataSettings, load_ingest
from ge.ingest.wikidata import (
    CityElevation,
    city_elevation,
    coordinates,
    match_stadium,
    to_metres,
)
from ge.ingest.wikidata import label as wd_label

STADIUMS_PATH = REPO_ROOT / "config" / "stadiums.yaml"
OVERRIDES_PATH = REPO_ROOT / "config" / "stadium_overrides.yaml"
_QID = re.compile(r"^Q\d+$")
_OVERRIDE_KEYS = {"stadium_id", "name", "qid", "approved_by", "approved_on", "reason"}


class Wiki(Protocol):
    def search(self, name: str) -> dict[str, Any]: ...
    def entities(self, qids: list[str]) -> dict[str, Any]: ...


def load_overrides(path: Path = OVERRIDES_PATH) -> list[dict[str, Any]]:
    """User-approved Wikidata picks. Every entry must say who approved it and when."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    out = []
    for i, row in enumerate(data.get("overrides") or []):
        missing = _OVERRIDE_KEYS - set(row)
        extra = set(row) - _OVERRIDE_KEYS
        if missing or extra:
            raise ValueError(f"{path} entry {i}: missing {sorted(missing)}, extra {sorted(extra)}")
        if not _QID.match(str(row["qid"])):
            raise ValueError(f"{path} entry {i}: qid {row['qid']!r} is not a Wikidata item id")
        if not str(row["approved_by"]).strip() or not str(row["approved_on"]).strip():
            raise ValueError(f"{path} entry {i}: approved_by and approved_on are required")
        out.append({**row, "approved_on": str(row["approved_on"])})
    return out


def build_stadiums(
    schedules: pl.DataFrame,
    wiki: Wiki,
    cfg: WikidataSettings,
    current_season: int,
    overrides: list[dict[str, Any]],
    units: ElevationUnits | None = None,
) -> list[dict[str, Any]]:
    """DATA-13: one row per (stadium_id, name), located only via Wikidata."""
    venues = (
        schedules.filter(pl.col("stadium").is_not_null())
        .group_by(["stadium_id", "stadium"])
        .agg(pl.col("season").unique().sort().alias("seasons"), pl.col("roof").unique())
        .sort(["stadium_id", "stadium"])
    )
    ov = {(o["stadium_id"], o["name"]): o for o in overrides}
    names = sorted(set(venues["stadium"].to_list()))
    search = {n: wiki.search(n) for n in names}
    qids = {h["id"] for r in search.values() for h in r.get("search", [])}
    qids |= {o["qid"] for o in overrides}
    entities = wiki.entities(sorted(qids))

    tf = TimezoneFinder()
    prop = cfg.coordinate_property.value
    prefix = cfg.item_url_prefix.value
    rows: list[dict[str, Any]] = []
    for rec in venues.iter_rows(named=True):
        key = (rec["stadium_id"], rec["stadium"])
        lat: float | None
        lon: float | None
        qid: str | None
        if key in ov:
            o = ov[key]
            xy = coordinates(entities.get(o["qid"]) or {}, prop)
            if xy is None:
                raise ValueError(f"override {key} -> {o['qid']}: item has no coordinate location")
            label = wd_label(entities[o["qid"]])
            status, qid, lat, lon = "override", o["qid"], xy[0], xy[1]
            reason = f"approved by {o['approved_by']} on {o['approved_on']}: {o['reason']}"
        else:
            m = match_stadium([rec["stadium"]], search, entities, prop, prefix)
            status, qid, label, lat, lon, reason = m.status, m.qid, m.label, m.lat, m.lon, m.reason
        tz = tf.timezone_at(lng=lon, lat=lat) if lat is not None and lon is not None else None
        rows.append(
            {
                "stadium_id": rec["stadium_id"],
                "name": rec["stadium"],
                "seasons": [int(s) for s in rec["seasons"]],
                "has_current_season_game": current_season in rec["seasons"],
                "roof_values_seen": sorted(rec["roof"], key=lambda r: (r is None, r or "")),
                "match_status": status,
                "match_reason": reason,
                "wikidata_label": label,
                "lat": lat,
                "lon": lon,
                "timezone": tz,
                "source_url": prefix + qid if qid else None,
                "_qid": qid,
            }
        )
    unused = sorted(set(ov) - {(r["stadium_id"], r["name"]) for r in rows})
    _add_city_elevation(rows, entities, wiki, cfg, units or load_ingest().wikidata_units)
    if unused:
        raise ValueError(f"overrides for venues not in the schedules: {unused}")
    return rows


def _add_city_elevation(
    rows: list[dict[str, Any]],
    entities: dict[str, Any],
    wiki: Wiki,
    cfg: WikidataSettings,
    units: ElevationUnits,
) -> None:
    """ENV-02 city_elevation_proxy (user decisions 2026-09-29/30): P131 place, walking up
    its P131 chain to the first P2044; stored in metres with the original value and unit."""
    loc, elev_prop, prefix = (
        cfg.located_in_property.value,
        cfg.elevation_property.value,
        cfg.item_url_prefix.value,
    )
    cache: dict[str, Any] = {}

    def fetch(qids: list[str]) -> dict[str, Any]:
        todo = sorted(q for q in set(qids) if q not in cache)
        if todo:
            cache.update(wiki.entities(todo))
        return {q: cache[q] for q in qids if q in cache}

    for r in rows:
        qid = r.pop("_qid")
        if qid:
            e = city_elevation(entities[qid], fetch, loc, elev_prop)
        else:
            e = CityElevation(None, None, None, None, "no Wikidata item for this venue")
        metres = to_metres(e.value, e.unit, units) if e.value is not None and e.unit else None
        r.update(
            elevation_m=metres,
            elevation_original_value=e.value,
            elevation_original_unit=e.unit,
            elevation_method=e.method,
            elevation_place=e.place_label,
            elevation_chain=e.chain,
            elevation_source_url=prefix + e.place_qid if e.place_qid else None,
            elevation_reason=e.reason,
        )


def write_stadiums(
    rows: list[dict[str, Any]], current_season: int, path: Path = STADIUMS_PATH
) -> None:
    body = {
        "generated_by": "ge ingest stadiums",
        "generated_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"),
        "sources": "stadiums and roof: nflverse schedules (DATA-04); coordinates: Wikidata "
        "(DATA-13, CC0), exact match or user-approved override; timezone: timezonefinder",
        "current_season": current_season,
        "stadiums": rows,
    }
    path.write_text(yaml.safe_dump(body, sort_keys=False, allow_unicode=True), encoding="utf-8")


def load_stadiums(path: Path = STADIUMS_PATH) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return list(data["stadiums"])


def stadium_for_game(
    rows: list[dict[str, Any]], stadium_id: str, name: str | None
) -> dict[str, Any] | None:
    for r in rows:
        if r["stadium_id"] == stadium_id and r["name"] == name:
            return r
    return None


def missing_for_2026(rows: list[dict[str, Any]]) -> list[str]:
    """BUILD_PLAN check: current-season venues lacking coordinates or a source_url."""
    problems = []
    for r in rows:
        if not r["has_current_season_game"]:
            continue
        missing = [k for k in ("lat", "lon", "source_url") if r.get(k) is None]
        if missing:
            problems.append(
                f"{r['stadium_id']} {r['name']!r}: missing {missing} "
                f"({r['match_status']}: {r['match_reason']})"
            )
    return problems
